//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationApi.srTipoDeporte {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BETipoDeporte", Namespace="http://schemas.datacontract.org/2004/07/ReservationREST.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class BETipoDeporte : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_MNSG_ERROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_TIPO_DEPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TIPO_DEPOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_MNSG_ERRO {
            get {
                return this.ALF_MNSG_ERROField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_MNSG_ERROField, value) != true)) {
                    this.ALF_MNSG_ERROField = value;
                    this.RaisePropertyChanged("ALF_MNSG_ERRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_TIPO_DEPO {
            get {
                return this.ALF_TIPO_DEPOField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_TIPO_DEPOField, value) != true)) {
                    this.ALF_TIPO_DEPOField = value;
                    this.RaisePropertyChanged("ALF_TIPO_DEPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TIPO_DEPO {
            get {
                return this.COD_TIPO_DEPOField;
            }
            set {
                if ((this.COD_TIPO_DEPOField.Equals(value) != true)) {
                    this.COD_TIPO_DEPOField = value;
                    this.RaisePropertyChanged("COD_TIPO_DEPO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srTipoDeporte.ITipoDeporte")]
    public interface ITipoDeporte {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoDeporte/Listar_TiposDeporte", ReplyAction="http://tempuri.org/ITipoDeporte/Listar_TiposDeporteResponse")]
        ReservationApi.srTipoDeporte.BETipoDeporte[] Listar_TiposDeporte();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoDeporte/Listar_TiposDeporte", ReplyAction="http://tempuri.org/ITipoDeporte/Listar_TiposDeporteResponse")]
        System.Threading.Tasks.Task<ReservationApi.srTipoDeporte.BETipoDeporte[]> Listar_TiposDeporteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoDeporte/Registrar_TipoDeporte", ReplyAction="http://tempuri.org/ITipoDeporte/Registrar_TipoDeporteResponse")]
        ReservationApi.srTipoDeporte.BETipoDeporte Registrar_TipoDeporte(ReservationApi.srTipoDeporte.BETipoDeporte obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoDeporte/Registrar_TipoDeporte", ReplyAction="http://tempuri.org/ITipoDeporte/Registrar_TipoDeporteResponse")]
        System.Threading.Tasks.Task<ReservationApi.srTipoDeporte.BETipoDeporte> Registrar_TipoDeporteAsync(ReservationApi.srTipoDeporte.BETipoDeporte obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoDeporte/Actualizar_TipoDeporte", ReplyAction="http://tempuri.org/ITipoDeporte/Actualizar_TipoDeporteResponse")]
        ReservationApi.srTipoDeporte.BETipoDeporte Actualizar_TipoDeporte(ReservationApi.srTipoDeporte.BETipoDeporte obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoDeporte/Actualizar_TipoDeporte", ReplyAction="http://tempuri.org/ITipoDeporte/Actualizar_TipoDeporteResponse")]
        System.Threading.Tasks.Task<ReservationApi.srTipoDeporte.BETipoDeporte> Actualizar_TipoDeporteAsync(ReservationApi.srTipoDeporte.BETipoDeporte obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoDeporte/Obtener_TipoDeporte", ReplyAction="http://tempuri.org/ITipoDeporte/Obtener_TipoDeporteResponse")]
        ReservationApi.srTipoDeporte.BETipoDeporte[] Obtener_TipoDeporte(string COD_TIPO_DEPO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoDeporte/Obtener_TipoDeporte", ReplyAction="http://tempuri.org/ITipoDeporte/Obtener_TipoDeporteResponse")]
        System.Threading.Tasks.Task<ReservationApi.srTipoDeporte.BETipoDeporte[]> Obtener_TipoDeporteAsync(string COD_TIPO_DEPO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoDeporte/Eliminar_TipoDeporte", ReplyAction="http://tempuri.org/ITipoDeporte/Eliminar_TipoDeporteResponse")]
        void Eliminar_TipoDeporte(string COD_TIPO_DEPO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipoDeporte/Eliminar_TipoDeporte", ReplyAction="http://tempuri.org/ITipoDeporte/Eliminar_TipoDeporteResponse")]
        System.Threading.Tasks.Task Eliminar_TipoDeporteAsync(string COD_TIPO_DEPO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITipoDeporteChannel : ReservationApi.srTipoDeporte.ITipoDeporte, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoDeporteClient : System.ServiceModel.ClientBase<ReservationApi.srTipoDeporte.ITipoDeporte>, ReservationApi.srTipoDeporte.ITipoDeporte {
        
        public TipoDeporteClient() {
        }
        
        public TipoDeporteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoDeporteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoDeporteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoDeporteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReservationApi.srTipoDeporte.BETipoDeporte[] Listar_TiposDeporte() {
            return base.Channel.Listar_TiposDeporte();
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srTipoDeporte.BETipoDeporte[]> Listar_TiposDeporteAsync() {
            return base.Channel.Listar_TiposDeporteAsync();
        }
        
        public ReservationApi.srTipoDeporte.BETipoDeporte Registrar_TipoDeporte(ReservationApi.srTipoDeporte.BETipoDeporte obj) {
            return base.Channel.Registrar_TipoDeporte(obj);
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srTipoDeporte.BETipoDeporte> Registrar_TipoDeporteAsync(ReservationApi.srTipoDeporte.BETipoDeporte obj) {
            return base.Channel.Registrar_TipoDeporteAsync(obj);
        }
        
        public ReservationApi.srTipoDeporte.BETipoDeporte Actualizar_TipoDeporte(ReservationApi.srTipoDeporte.BETipoDeporte obj) {
            return base.Channel.Actualizar_TipoDeporte(obj);
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srTipoDeporte.BETipoDeporte> Actualizar_TipoDeporteAsync(ReservationApi.srTipoDeporte.BETipoDeporte obj) {
            return base.Channel.Actualizar_TipoDeporteAsync(obj);
        }
        
        public ReservationApi.srTipoDeporte.BETipoDeporte[] Obtener_TipoDeporte(string COD_TIPO_DEPO) {
            return base.Channel.Obtener_TipoDeporte(COD_TIPO_DEPO);
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srTipoDeporte.BETipoDeporte[]> Obtener_TipoDeporteAsync(string COD_TIPO_DEPO) {
            return base.Channel.Obtener_TipoDeporteAsync(COD_TIPO_DEPO);
        }
        
        public void Eliminar_TipoDeporte(string COD_TIPO_DEPO) {
            base.Channel.Eliminar_TipoDeporte(COD_TIPO_DEPO);
        }
        
        public System.Threading.Tasks.Task Eliminar_TipoDeporteAsync(string COD_TIPO_DEPO) {
            return base.Channel.Eliminar_TipoDeporteAsync(COD_TIPO_DEPO);
        }
    }
}
