//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationApi.srReservation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BETypeSport", Namespace="http://schemas.datacontract.org/2004/07/ReservationServices.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class BETypeSport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_TIPO_DEPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TIPO_DEPOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_TIPO_DEPO {
            get {
                return this.ALF_TIPO_DEPOField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_TIPO_DEPOField, value) != true)) {
                    this.ALF_TIPO_DEPOField = value;
                    this.RaisePropertyChanged("ALF_TIPO_DEPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TIPO_DEPO {
            get {
                return this.COD_TIPO_DEPOField;
            }
            set {
                if ((this.COD_TIPO_DEPOField.Equals(value) != true)) {
                    this.COD_TIPO_DEPOField = value;
                    this.RaisePropertyChanged("COD_TIPO_DEPO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BETypeCourts", Namespace="http://schemas.datacontract.org/2004/07/ReservationServices.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class BETypeCourts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_TIPO_CANCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TIPO_CANCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TIPO_DEPOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_TIPO_CANC {
            get {
                return this.ALF_TIPO_CANCField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_TIPO_CANCField, value) != true)) {
                    this.ALF_TIPO_CANCField = value;
                    this.RaisePropertyChanged("ALF_TIPO_CANC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TIPO_CANC {
            get {
                return this.COD_TIPO_CANCField;
            }
            set {
                if ((this.COD_TIPO_CANCField.Equals(value) != true)) {
                    this.COD_TIPO_CANCField = value;
                    this.RaisePropertyChanged("COD_TIPO_CANC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TIPO_DEPO {
            get {
                return this.COD_TIPO_DEPOField;
            }
            set {
                if ((this.COD_TIPO_DEPOField.Equals(value) != true)) {
                    this.COD_TIPO_DEPOField = value;
                    this.RaisePropertyChanged("COD_TIPO_DEPO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BETimeTable", Namespace="http://schemas.datacontract.org/2004/07/ReservationServices.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class BETimeTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_HORAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_HORAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HOR_FINAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HOR_INICField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_HORA {
            get {
                return this.ALF_HORAField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_HORAField, value) != true)) {
                    this.ALF_HORAField = value;
                    this.RaisePropertyChanged("ALF_HORA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_HORA {
            get {
                return this.COD_HORAField;
            }
            set {
                if ((this.COD_HORAField.Equals(value) != true)) {
                    this.COD_HORAField = value;
                    this.RaisePropertyChanged("COD_HORA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HOR_FINA {
            get {
                return this.HOR_FINAField;
            }
            set {
                if ((object.ReferenceEquals(this.HOR_FINAField, value) != true)) {
                    this.HOR_FINAField = value;
                    this.RaisePropertyChanged("HOR_FINA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HOR_INIC {
            get {
                return this.HOR_INICField;
            }
            set {
                if ((object.ReferenceEquals(this.HOR_INICField, value) != true)) {
                    this.HOR_INICField = value;
                    this.RaisePropertyChanged("HOR_INIC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEOrder", Namespace="http://schemas.datacontract.org/2004/07/ReservationServices.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class BEOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_CORRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_HORAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_MNSG_ERROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_NOMBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_NUME_DOCUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_NUME_PEDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_NUME_TELEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_TIPO_CANCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_TIPO_DEPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_TIPO_DOCUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_CLIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_HORAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_PEDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TIPO_CANCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TIPO_DEPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FEC_HORA_RESEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FEC_RESEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HOR_INICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IND_ESTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MON_DEUDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MON_PAGAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MON_PAGOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_CORR {
            get {
                return this.ALF_CORRField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_CORRField, value) != true)) {
                    this.ALF_CORRField = value;
                    this.RaisePropertyChanged("ALF_CORR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_HORA {
            get {
                return this.ALF_HORAField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_HORAField, value) != true)) {
                    this.ALF_HORAField = value;
                    this.RaisePropertyChanged("ALF_HORA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_MNSG_ERRO {
            get {
                return this.ALF_MNSG_ERROField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_MNSG_ERROField, value) != true)) {
                    this.ALF_MNSG_ERROField = value;
                    this.RaisePropertyChanged("ALF_MNSG_ERRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_NOMB {
            get {
                return this.ALF_NOMBField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_NOMBField, value) != true)) {
                    this.ALF_NOMBField = value;
                    this.RaisePropertyChanged("ALF_NOMB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_NUME_DOCU {
            get {
                return this.ALF_NUME_DOCUField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_NUME_DOCUField, value) != true)) {
                    this.ALF_NUME_DOCUField = value;
                    this.RaisePropertyChanged("ALF_NUME_DOCU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_NUME_PEDI {
            get {
                return this.ALF_NUME_PEDIField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_NUME_PEDIField, value) != true)) {
                    this.ALF_NUME_PEDIField = value;
                    this.RaisePropertyChanged("ALF_NUME_PEDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_NUME_TELE {
            get {
                return this.ALF_NUME_TELEField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_NUME_TELEField, value) != true)) {
                    this.ALF_NUME_TELEField = value;
                    this.RaisePropertyChanged("ALF_NUME_TELE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_TIPO_CANC {
            get {
                return this.ALF_TIPO_CANCField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_TIPO_CANCField, value) != true)) {
                    this.ALF_TIPO_CANCField = value;
                    this.RaisePropertyChanged("ALF_TIPO_CANC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_TIPO_DEPO {
            get {
                return this.ALF_TIPO_DEPOField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_TIPO_DEPOField, value) != true)) {
                    this.ALF_TIPO_DEPOField = value;
                    this.RaisePropertyChanged("ALF_TIPO_DEPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_TIPO_DOCU {
            get {
                return this.ALF_TIPO_DOCUField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_TIPO_DOCUField, value) != true)) {
                    this.ALF_TIPO_DOCUField = value;
                    this.RaisePropertyChanged("ALF_TIPO_DOCU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_CLIE {
            get {
                return this.COD_CLIEField;
            }
            set {
                if ((this.COD_CLIEField.Equals(value) != true)) {
                    this.COD_CLIEField = value;
                    this.RaisePropertyChanged("COD_CLIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_HORA {
            get {
                return this.COD_HORAField;
            }
            set {
                if ((this.COD_HORAField.Equals(value) != true)) {
                    this.COD_HORAField = value;
                    this.RaisePropertyChanged("COD_HORA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_PEDI {
            get {
                return this.COD_PEDIField;
            }
            set {
                if ((this.COD_PEDIField.Equals(value) != true)) {
                    this.COD_PEDIField = value;
                    this.RaisePropertyChanged("COD_PEDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TIPO_CANC {
            get {
                return this.COD_TIPO_CANCField;
            }
            set {
                if ((this.COD_TIPO_CANCField.Equals(value) != true)) {
                    this.COD_TIPO_CANCField = value;
                    this.RaisePropertyChanged("COD_TIPO_CANC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TIPO_DEPO {
            get {
                return this.COD_TIPO_DEPOField;
            }
            set {
                if ((this.COD_TIPO_DEPOField.Equals(value) != true)) {
                    this.COD_TIPO_DEPOField = value;
                    this.RaisePropertyChanged("COD_TIPO_DEPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FEC_HORA_RESE {
            get {
                return this.FEC_HORA_RESEField;
            }
            set {
                if ((this.FEC_HORA_RESEField.Equals(value) != true)) {
                    this.FEC_HORA_RESEField = value;
                    this.RaisePropertyChanged("FEC_HORA_RESE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FEC_RESE {
            get {
                return this.FEC_RESEField;
            }
            set {
                if ((object.ReferenceEquals(this.FEC_RESEField, value) != true)) {
                    this.FEC_RESEField = value;
                    this.RaisePropertyChanged("FEC_RESE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HOR_INIC {
            get {
                return this.HOR_INICField;
            }
            set {
                if ((object.ReferenceEquals(this.HOR_INICField, value) != true)) {
                    this.HOR_INICField = value;
                    this.RaisePropertyChanged("HOR_INIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IND_ESTA {
            get {
                return this.IND_ESTAField;
            }
            set {
                if ((object.ReferenceEquals(this.IND_ESTAField, value) != true)) {
                    this.IND_ESTAField = value;
                    this.RaisePropertyChanged("IND_ESTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MON_DEUD {
            get {
                return this.MON_DEUDField;
            }
            set {
                if ((this.MON_DEUDField.Equals(value) != true)) {
                    this.MON_DEUDField = value;
                    this.RaisePropertyChanged("MON_DEUD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MON_PAGA {
            get {
                return this.MON_PAGAField;
            }
            set {
                if ((this.MON_PAGAField.Equals(value) != true)) {
                    this.MON_PAGAField = value;
                    this.RaisePropertyChanged("MON_PAGA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MON_PAGO {
            get {
                return this.MON_PAGOField;
            }
            set {
                if ((this.MON_PAGOField.Equals(value) != true)) {
                    this.MON_PAGOField = value;
                    this.RaisePropertyChanged("MON_PAGO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BELogin", Namespace="http://schemas.datacontract.org/2004/07/ReservationServices.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class BELogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_PASSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_USUAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_PASS {
            get {
                return this.ALF_PASSField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_PASSField, value) != true)) {
                    this.ALF_PASSField = value;
                    this.RaisePropertyChanged("ALF_PASS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_USUA {
            get {
                return this.COD_USUAField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_USUAField, value) != true)) {
                    this.COD_USUAField = value;
                    this.RaisePropertyChanged("COD_USUA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srReservation.IOrder")]
    public interface IOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/ListTypesSport", ReplyAction="http://tempuri.org/IOrder/ListTypesSportResponse")]
        ReservationApi.srReservation.BETypeSport[] ListTypesSport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/ListTypesSport", ReplyAction="http://tempuri.org/IOrder/ListTypesSportResponse")]
        System.Threading.Tasks.Task<ReservationApi.srReservation.BETypeSport[]> ListTypesSportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/ListTypeCourts", ReplyAction="http://tempuri.org/IOrder/ListTypeCourtsResponse")]
        ReservationApi.srReservation.BETypeCourts[] ListTypeCourts(int COD_TIPO_DEPO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/ListTypeCourts", ReplyAction="http://tempuri.org/IOrder/ListTypeCourtsResponse")]
        System.Threading.Tasks.Task<ReservationApi.srReservation.BETypeCourts[]> ListTypeCourtsAsync(int COD_TIPO_DEPO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/ListTimeTable", ReplyAction="http://tempuri.org/IOrder/ListTimeTableResponse")]
        ReservationApi.srReservation.BETimeTable[] ListTimeTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/ListTimeTable", ReplyAction="http://tempuri.org/IOrder/ListTimeTableResponse")]
        System.Threading.Tasks.Task<ReservationApi.srReservation.BETimeTable[]> ListTimeTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/SetOrder", ReplyAction="http://tempuri.org/IOrder/SetOrderResponse")]
        ReservationApi.srReservation.BEOrder SetOrder(ReservationApi.srReservation.BEOrder obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/SetOrder", ReplyAction="http://tempuri.org/IOrder/SetOrderResponse")]
        System.Threading.Tasks.Task<ReservationApi.srReservation.BEOrder> SetOrderAsync(ReservationApi.srReservation.BEOrder obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/ListReservation", ReplyAction="http://tempuri.org/IOrder/ListReservationResponse")]
        ReservationApi.srReservation.BEOrder[] ListReservation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/ListReservation", ReplyAction="http://tempuri.org/IOrder/ListReservationResponse")]
        System.Threading.Tasks.Task<ReservationApi.srReservation.BEOrder[]> ListReservationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/LoginUser", ReplyAction="http://tempuri.org/IOrder/LoginUserResponse")]
        int LoginUser(ReservationApi.srReservation.BELogin obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/LoginUser", ReplyAction="http://tempuri.org/IOrder/LoginUserResponse")]
        System.Threading.Tasks.Task<int> LoginUserAsync(ReservationApi.srReservation.BELogin obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderChannel : ReservationApi.srReservation.IOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderClient : System.ServiceModel.ClientBase<ReservationApi.srReservation.IOrder>, ReservationApi.srReservation.IOrder {
        
        public OrderClient() {
        }
        
        public OrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReservationApi.srReservation.BETypeSport[] ListTypesSport() {
            return base.Channel.ListTypesSport();
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srReservation.BETypeSport[]> ListTypesSportAsync() {
            return base.Channel.ListTypesSportAsync();
        }
        
        public ReservationApi.srReservation.BETypeCourts[] ListTypeCourts(int COD_TIPO_DEPO) {
            return base.Channel.ListTypeCourts(COD_TIPO_DEPO);
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srReservation.BETypeCourts[]> ListTypeCourtsAsync(int COD_TIPO_DEPO) {
            return base.Channel.ListTypeCourtsAsync(COD_TIPO_DEPO);
        }
        
        public ReservationApi.srReservation.BETimeTable[] ListTimeTable() {
            return base.Channel.ListTimeTable();
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srReservation.BETimeTable[]> ListTimeTableAsync() {
            return base.Channel.ListTimeTableAsync();
        }
        
        public ReservationApi.srReservation.BEOrder SetOrder(ReservationApi.srReservation.BEOrder obj) {
            return base.Channel.SetOrder(obj);
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srReservation.BEOrder> SetOrderAsync(ReservationApi.srReservation.BEOrder obj) {
            return base.Channel.SetOrderAsync(obj);
        }
        
        public ReservationApi.srReservation.BEOrder[] ListReservation() {
            return base.Channel.ListReservation();
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srReservation.BEOrder[]> ListReservationAsync() {
            return base.Channel.ListReservationAsync();
        }
        
        public int LoginUser(ReservationApi.srReservation.BELogin obj) {
            return base.Channel.LoginUser(obj);
        }
        
        public System.Threading.Tasks.Task<int> LoginUserAsync(ReservationApi.srReservation.BELogin obj) {
            return base.Channel.LoginUserAsync(obj);
        }
    }
}
