//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationApi.srReservation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BETipoDeporte", Namespace="http://schemas.datacontract.org/2004/07/ReservationServices.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class BETipoDeporte : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_TIPO_DEPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TIPO_DEPOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_TIPO_DEPO {
            get {
                return this.ALF_TIPO_DEPOField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_TIPO_DEPOField, value) != true)) {
                    this.ALF_TIPO_DEPOField = value;
                    this.RaisePropertyChanged("ALF_TIPO_DEPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TIPO_DEPO {
            get {
                return this.COD_TIPO_DEPOField;
            }
            set {
                if ((this.COD_TIPO_DEPOField.Equals(value) != true)) {
                    this.COD_TIPO_DEPOField = value;
                    this.RaisePropertyChanged("COD_TIPO_DEPO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BETipoCancha", Namespace="http://schemas.datacontract.org/2004/07/ReservationServices.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class BETipoCancha : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_TIPO_CANCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TIPO_CANCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TIPO_DEPOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_TIPO_CANC {
            get {
                return this.ALF_TIPO_CANCField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_TIPO_CANCField, value) != true)) {
                    this.ALF_TIPO_CANCField = value;
                    this.RaisePropertyChanged("ALF_TIPO_CANC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TIPO_CANC {
            get {
                return this.COD_TIPO_CANCField;
            }
            set {
                if ((this.COD_TIPO_CANCField.Equals(value) != true)) {
                    this.COD_TIPO_CANCField = value;
                    this.RaisePropertyChanged("COD_TIPO_CANC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TIPO_DEPO {
            get {
                return this.COD_TIPO_DEPOField;
            }
            set {
                if ((this.COD_TIPO_DEPOField.Equals(value) != true)) {
                    this.COD_TIPO_DEPOField = value;
                    this.RaisePropertyChanged("COD_TIPO_DEPO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEHorario", Namespace="http://schemas.datacontract.org/2004/07/ReservationServices.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class BEHorario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_HORAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_HORAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HOR_FINAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HOR_INICField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_HORA {
            get {
                return this.ALF_HORAField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_HORAField, value) != true)) {
                    this.ALF_HORAField = value;
                    this.RaisePropertyChanged("ALF_HORA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_HORA {
            get {
                return this.COD_HORAField;
            }
            set {
                if ((this.COD_HORAField.Equals(value) != true)) {
                    this.COD_HORAField = value;
                    this.RaisePropertyChanged("COD_HORA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HOR_FINA {
            get {
                return this.HOR_FINAField;
            }
            set {
                if ((object.ReferenceEquals(this.HOR_FINAField, value) != true)) {
                    this.HOR_FINAField = value;
                    this.RaisePropertyChanged("HOR_FINA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HOR_INIC {
            get {
                return this.HOR_INICField;
            }
            set {
                if ((object.ReferenceEquals(this.HOR_INICField, value) != true)) {
                    this.HOR_INICField = value;
                    this.RaisePropertyChanged("HOR_INIC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BECliente", Namespace="http://schemas.datacontract.org/2004/07/ReservationServices.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class BECliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_CORRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_MNSG_ERROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_NOMBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_NUME_DOCUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_NUME_TELEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_TIPO_DOCUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_CLIEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_CORR {
            get {
                return this.ALF_CORRField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_CORRField, value) != true)) {
                    this.ALF_CORRField = value;
                    this.RaisePropertyChanged("ALF_CORR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_MNSG_ERRO {
            get {
                return this.ALF_MNSG_ERROField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_MNSG_ERROField, value) != true)) {
                    this.ALF_MNSG_ERROField = value;
                    this.RaisePropertyChanged("ALF_MNSG_ERRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_NOMB {
            get {
                return this.ALF_NOMBField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_NOMBField, value) != true)) {
                    this.ALF_NOMBField = value;
                    this.RaisePropertyChanged("ALF_NOMB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_NUME_DOCU {
            get {
                return this.ALF_NUME_DOCUField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_NUME_DOCUField, value) != true)) {
                    this.ALF_NUME_DOCUField = value;
                    this.RaisePropertyChanged("ALF_NUME_DOCU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_NUME_TELE {
            get {
                return this.ALF_NUME_TELEField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_NUME_TELEField, value) != true)) {
                    this.ALF_NUME_TELEField = value;
                    this.RaisePropertyChanged("ALF_NUME_TELE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_TIPO_DOCU {
            get {
                return this.ALF_TIPO_DOCUField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_TIPO_DOCUField, value) != true)) {
                    this.ALF_TIPO_DOCUField = value;
                    this.RaisePropertyChanged("ALF_TIPO_DOCU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_CLIE {
            get {
                return this.COD_CLIEField;
            }
            set {
                if ((this.COD_CLIEField.Equals(value) != true)) {
                    this.COD_CLIEField = value;
                    this.RaisePropertyChanged("COD_CLIE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEOrden", Namespace="http://schemas.datacontract.org/2004/07/ReservationServices.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class BEOrden : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_CORRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_HORAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_MNSG_ERROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_NOMBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_NUME_DOCUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_NUME_PEDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_NUME_TELEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_TIPO_CANCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_TIPO_DEPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_TIPO_DOCUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_CLIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_HORAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_PEDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_RESEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TIPO_CANCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TIPO_DEPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FEC_HORA_RESEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FEC_RESEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HOR_INICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IND_ESTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MON_DEUDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MON_PAGAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MON_PAGOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_CORR {
            get {
                return this.ALF_CORRField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_CORRField, value) != true)) {
                    this.ALF_CORRField = value;
                    this.RaisePropertyChanged("ALF_CORR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_HORA {
            get {
                return this.ALF_HORAField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_HORAField, value) != true)) {
                    this.ALF_HORAField = value;
                    this.RaisePropertyChanged("ALF_HORA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_MNSG_ERRO {
            get {
                return this.ALF_MNSG_ERROField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_MNSG_ERROField, value) != true)) {
                    this.ALF_MNSG_ERROField = value;
                    this.RaisePropertyChanged("ALF_MNSG_ERRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_NOMB {
            get {
                return this.ALF_NOMBField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_NOMBField, value) != true)) {
                    this.ALF_NOMBField = value;
                    this.RaisePropertyChanged("ALF_NOMB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_NUME_DOCU {
            get {
                return this.ALF_NUME_DOCUField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_NUME_DOCUField, value) != true)) {
                    this.ALF_NUME_DOCUField = value;
                    this.RaisePropertyChanged("ALF_NUME_DOCU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_NUME_PEDI {
            get {
                return this.ALF_NUME_PEDIField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_NUME_PEDIField, value) != true)) {
                    this.ALF_NUME_PEDIField = value;
                    this.RaisePropertyChanged("ALF_NUME_PEDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_NUME_TELE {
            get {
                return this.ALF_NUME_TELEField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_NUME_TELEField, value) != true)) {
                    this.ALF_NUME_TELEField = value;
                    this.RaisePropertyChanged("ALF_NUME_TELE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_TIPO_CANC {
            get {
                return this.ALF_TIPO_CANCField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_TIPO_CANCField, value) != true)) {
                    this.ALF_TIPO_CANCField = value;
                    this.RaisePropertyChanged("ALF_TIPO_CANC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_TIPO_DEPO {
            get {
                return this.ALF_TIPO_DEPOField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_TIPO_DEPOField, value) != true)) {
                    this.ALF_TIPO_DEPOField = value;
                    this.RaisePropertyChanged("ALF_TIPO_DEPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_TIPO_DOCU {
            get {
                return this.ALF_TIPO_DOCUField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_TIPO_DOCUField, value) != true)) {
                    this.ALF_TIPO_DOCUField = value;
                    this.RaisePropertyChanged("ALF_TIPO_DOCU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_CLIE {
            get {
                return this.COD_CLIEField;
            }
            set {
                if ((this.COD_CLIEField.Equals(value) != true)) {
                    this.COD_CLIEField = value;
                    this.RaisePropertyChanged("COD_CLIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_HORA {
            get {
                return this.COD_HORAField;
            }
            set {
                if ((this.COD_HORAField.Equals(value) != true)) {
                    this.COD_HORAField = value;
                    this.RaisePropertyChanged("COD_HORA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_PEDI {
            get {
                return this.COD_PEDIField;
            }
            set {
                if ((this.COD_PEDIField.Equals(value) != true)) {
                    this.COD_PEDIField = value;
                    this.RaisePropertyChanged("COD_PEDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_RESE {
            get {
                return this.COD_RESEField;
            }
            set {
                if ((this.COD_RESEField.Equals(value) != true)) {
                    this.COD_RESEField = value;
                    this.RaisePropertyChanged("COD_RESE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TIPO_CANC {
            get {
                return this.COD_TIPO_CANCField;
            }
            set {
                if ((this.COD_TIPO_CANCField.Equals(value) != true)) {
                    this.COD_TIPO_CANCField = value;
                    this.RaisePropertyChanged("COD_TIPO_CANC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TIPO_DEPO {
            get {
                return this.COD_TIPO_DEPOField;
            }
            set {
                if ((this.COD_TIPO_DEPOField.Equals(value) != true)) {
                    this.COD_TIPO_DEPOField = value;
                    this.RaisePropertyChanged("COD_TIPO_DEPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FEC_HORA_RESE {
            get {
                return this.FEC_HORA_RESEField;
            }
            set {
                if ((this.FEC_HORA_RESEField.Equals(value) != true)) {
                    this.FEC_HORA_RESEField = value;
                    this.RaisePropertyChanged("FEC_HORA_RESE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FEC_RESE {
            get {
                return this.FEC_RESEField;
            }
            set {
                if ((object.ReferenceEquals(this.FEC_RESEField, value) != true)) {
                    this.FEC_RESEField = value;
                    this.RaisePropertyChanged("FEC_RESE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HOR_INIC {
            get {
                return this.HOR_INICField;
            }
            set {
                if ((object.ReferenceEquals(this.HOR_INICField, value) != true)) {
                    this.HOR_INICField = value;
                    this.RaisePropertyChanged("HOR_INIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IND_ESTA {
            get {
                return this.IND_ESTAField;
            }
            set {
                if ((object.ReferenceEquals(this.IND_ESTAField, value) != true)) {
                    this.IND_ESTAField = value;
                    this.RaisePropertyChanged("IND_ESTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MON_DEUD {
            get {
                return this.MON_DEUDField;
            }
            set {
                if ((this.MON_DEUDField.Equals(value) != true)) {
                    this.MON_DEUDField = value;
                    this.RaisePropertyChanged("MON_DEUD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MON_PAGA {
            get {
                return this.MON_PAGAField;
            }
            set {
                if ((this.MON_PAGAField.Equals(value) != true)) {
                    this.MON_PAGAField = value;
                    this.RaisePropertyChanged("MON_PAGA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MON_PAGO {
            get {
                return this.MON_PAGOField;
            }
            set {
                if ((this.MON_PAGOField.Equals(value) != true)) {
                    this.MON_PAGOField = value;
                    this.RaisePropertyChanged("MON_PAGO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BELogin", Namespace="http://schemas.datacontract.org/2004/07/ReservationServices.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class BELogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_PASSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_USUAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_PASS {
            get {
                return this.ALF_PASSField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_PASSField, value) != true)) {
                    this.ALF_PASSField = value;
                    this.RaisePropertyChanged("ALF_PASS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_USUA {
            get {
                return this.COD_USUAField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_USUAField, value) != true)) {
                    this.COD_USUAField = value;
                    this.RaisePropertyChanged("COD_USUA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srReservation.IOrden")]
    public interface IOrden {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/Listar_TiposDeporte", ReplyAction="http://tempuri.org/IOrden/Listar_TiposDeporteResponse")]
        ReservationApi.srReservation.BETipoDeporte[] Listar_TiposDeporte();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/Listar_TiposDeporte", ReplyAction="http://tempuri.org/IOrden/Listar_TiposDeporteResponse")]
        System.Threading.Tasks.Task<ReservationApi.srReservation.BETipoDeporte[]> Listar_TiposDeporteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/Listar_TiposCancha", ReplyAction="http://tempuri.org/IOrden/Listar_TiposCanchaResponse")]
        ReservationApi.srReservation.BETipoCancha[] Listar_TiposCancha(int COD_TIPO_DEPO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/Listar_TiposCancha", ReplyAction="http://tempuri.org/IOrden/Listar_TiposCanchaResponse")]
        System.Threading.Tasks.Task<ReservationApi.srReservation.BETipoCancha[]> Listar_TiposCanchaAsync(int COD_TIPO_DEPO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/Listar_Horarios", ReplyAction="http://tempuri.org/IOrden/Listar_HorariosResponse")]
        ReservationApi.srReservation.BEHorario[] Listar_Horarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/Listar_Horarios", ReplyAction="http://tempuri.org/IOrden/Listar_HorariosResponse")]
        System.Threading.Tasks.Task<ReservationApi.srReservation.BEHorario[]> Listar_HorariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/Registrar_Cliente", ReplyAction="http://tempuri.org/IOrden/Registrar_ClienteResponse")]
        ReservationApi.srReservation.BECliente Registrar_Cliente(ReservationApi.srReservation.BECliente obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/Registrar_Cliente", ReplyAction="http://tempuri.org/IOrden/Registrar_ClienteResponse")]
        System.Threading.Tasks.Task<ReservationApi.srReservation.BECliente> Registrar_ClienteAsync(ReservationApi.srReservation.BECliente obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/Registrar_Orden", ReplyAction="http://tempuri.org/IOrden/Registrar_OrdenResponse")]
        ReservationApi.srReservation.BEOrden Registrar_Orden(ReservationApi.srReservation.BEOrden obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/Registrar_Orden", ReplyAction="http://tempuri.org/IOrden/Registrar_OrdenResponse")]
        System.Threading.Tasks.Task<ReservationApi.srReservation.BEOrden> Registrar_OrdenAsync(ReservationApi.srReservation.BEOrden obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/Listar_Reservaciones", ReplyAction="http://tempuri.org/IOrden/Listar_ReservacionesResponse")]
        ReservationApi.srReservation.BEOrden[] Listar_Reservaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/Listar_Reservaciones", ReplyAction="http://tempuri.org/IOrden/Listar_ReservacionesResponse")]
        System.Threading.Tasks.Task<ReservationApi.srReservation.BEOrden[]> Listar_ReservacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/LoginUser", ReplyAction="http://tempuri.org/IOrden/LoginUserResponse")]
        int LoginUser(ReservationApi.srReservation.BELogin obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrden/LoginUser", ReplyAction="http://tempuri.org/IOrden/LoginUserResponse")]
        System.Threading.Tasks.Task<int> LoginUserAsync(ReservationApi.srReservation.BELogin obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdenChannel : ReservationApi.srReservation.IOrden, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenClient : System.ServiceModel.ClientBase<ReservationApi.srReservation.IOrden>, ReservationApi.srReservation.IOrden {
        
        public OrdenClient() {
        }
        
        public OrdenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReservationApi.srReservation.BETipoDeporte[] Listar_TiposDeporte() {
            return base.Channel.Listar_TiposDeporte();
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srReservation.BETipoDeporte[]> Listar_TiposDeporteAsync() {
            return base.Channel.Listar_TiposDeporteAsync();
        }
        
        public ReservationApi.srReservation.BETipoCancha[] Listar_TiposCancha(int COD_TIPO_DEPO) {
            return base.Channel.Listar_TiposCancha(COD_TIPO_DEPO);
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srReservation.BETipoCancha[]> Listar_TiposCanchaAsync(int COD_TIPO_DEPO) {
            return base.Channel.Listar_TiposCanchaAsync(COD_TIPO_DEPO);
        }
        
        public ReservationApi.srReservation.BEHorario[] Listar_Horarios() {
            return base.Channel.Listar_Horarios();
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srReservation.BEHorario[]> Listar_HorariosAsync() {
            return base.Channel.Listar_HorariosAsync();
        }
        
        public ReservationApi.srReservation.BECliente Registrar_Cliente(ReservationApi.srReservation.BECliente obj) {
            return base.Channel.Registrar_Cliente(obj);
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srReservation.BECliente> Registrar_ClienteAsync(ReservationApi.srReservation.BECliente obj) {
            return base.Channel.Registrar_ClienteAsync(obj);
        }
        
        public ReservationApi.srReservation.BEOrden Registrar_Orden(ReservationApi.srReservation.BEOrden obj) {
            return base.Channel.Registrar_Orden(obj);
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srReservation.BEOrden> Registrar_OrdenAsync(ReservationApi.srReservation.BEOrden obj) {
            return base.Channel.Registrar_OrdenAsync(obj);
        }
        
        public ReservationApi.srReservation.BEOrden[] Listar_Reservaciones() {
            return base.Channel.Listar_Reservaciones();
        }
        
        public System.Threading.Tasks.Task<ReservationApi.srReservation.BEOrden[]> Listar_ReservacionesAsync() {
            return base.Channel.Listar_ReservacionesAsync();
        }
        
        public int LoginUser(ReservationApi.srReservation.BELogin obj) {
            return base.Channel.LoginUser(obj);
        }
        
        public System.Threading.Tasks.Task<int> LoginUserAsync(ReservationApi.srReservation.BELogin obj) {
            return base.Channel.LoginUserAsync(obj);
        }
    }
}
